# syntax=docker/dockerfile:1.7

FROM golang:1.26.3-trixie AS builder

ARG BUILD_VERSION="docker debug"

WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -trimpath \
    -ldflags="-s -w -X 'github.com/alikonhz/pglogrepl2json/replicator.Version=${BUILD_VERSION}'" \
    -o /out/pg2redis ./pg2redis/cmd/main.go

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /out/pg2redis /bin/pg2redis

USER nonroot:nonroot

ENTRYPOINT ["/bin/pg2redis"]
